<?php
/**
 * Plugin Name: FarmNeed MCP Bootstrap Tools
 * Description: Temporary safe plugin-source tools for upgrading FarmNeed MCP.
 * Version: 1.0.0
 * Author: FarmNeed
 * Requires at least: 6.9
 * Requires PHP: 8.0
 */
if (!defined('ABSPATH')) exit;
final class FN_MCP_Bootstrap {
 const CAT='farmneed-mcp-bootstrap', MAX=2097152;
 static array $ext=['php','css','js','json','html','txt','md','xml','svg'];
 static function init(){add_action('wp_abilities_api_categories_init',[__CLASS__,'cat']);add_action('wp_abilities_api_init',[__CLASS__,'abilities']);}
 static function cat(){if(function_exists('wp_register_ability_category'))wp_register_ability_category(self::CAT,['label'=>'FarmNeed MCP Bootstrap','description'=>'Safe temporary abilities for FarmNeed MCP plugin source upgrades.']);}
 static function meta($ro=false,$d=false){return ['public'=>true,'show_in_rest'=>true,'mcp'=>['public'=>true],'annotations'=>['readonly'=>$ro,'destructive'=>$d,'idempotent'=>$ro]];}
 static function schema($p=[],$r=[]){$s=['type'=>'object','properties'=>$p,'additionalProperties'=>false];if($r)$s['required']=$r;return $s;}
 static function out(){return ['type'=>'object','additionalProperties'=>true];}
 static function reg($n,$l,$d,$in,$cb,$m){wp_register_ability($n,['label'=>$l,'description'=>$d,'category'=>self::CAT,'input_schema'=>$in,'output_schema'=>self::out(),'execute_callback'=>[__CLASS__,$cb],'permission_callback'=>[__CLASS__,'can'],'meta'=>$m]);}
 static function abilities(){if(!function_exists('wp_register_ability'))return;$pl=['type'=>'string','minLength'=>1,'maxLength'=>190];$pa=['type'=>'string','minLength'=>1,'maxLength'=>500];
  self::reg('farmneed-bootstrap/list-plugin-files','List plugin files','List safe source files in an installed plugin with SHA-256 tokens.',self::schema(['plugin'=>$pl,'limit'=>['type'=>'integer','minimum'=>1,'maximum'=>2000]],['plugin']),'list_files',self::meta(true));
  self::reg('farmneed-bootstrap/read-plugin-file','Read plugin file','Read an allowlisted plugin source file with SHA-256 conflict token.',self::schema(['plugin'=>$pl,'path'=>$pa],['plugin','path']),'read_file',self::meta(true));
  self::reg('farmneed-bootstrap/update-plugin-file','Update plugin file','Conflict-safe plugin source update with automatic backup and PHP syntax validation.',self::schema(['plugin'=>$pl,'path'=>$pa,'content'=>['type'=>'string','maxLength'=>self::MAX],'expected_sha256'=>['type'=>'string','pattern'=>'^[a-fA-F0-9]{64}$']],['plugin','path','content','expected_sha256']),'update_file',self::meta(false,true));
  self::reg('farmneed-bootstrap/create-plugin-file','Create plugin file','Create a new allowlisted source file inside an installed plugin. Existing files are not overwritten.',self::schema(['plugin'=>$pl,'path'=>$pa,'content'=>['type'=>'string','maxLength'=>self::MAX]],['plugin','path','content']),'create_file',self::meta(false,false));
  self::reg('farmneed-bootstrap/backup-plugin','Backup plugin','Copy an installed plugin to a timestamped backup under uploads before a larger upgrade.',self::schema(['plugin'=>$pl],['plugin']),'backup_plugin',self::meta(false,false));
 }
 static function can(){return current_user_can('manage_options');}
 static function ok($a=[]){return array_merge(['ok'=>true,'bootstrap'=>'1.0.0'],$a);}
 static function err($c,$m,$d=[]){return new WP_Error($c,$m,$d);}
 static function root($p){$p=trim(str_replace('\\','/',wp_unslash((string)$p)),'/');if(!$p||str_contains($p,'..')||preg_match('/[^A-Za-z0-9._\/-]/',$p))return self::err('invalid_plugin','Invalid plugin identifier.');$slug=explode('/',$p)[0];$r=realpath(WP_PLUGIN_DIR.'/'.$slug);$base=realpath(WP_PLUGIN_DIR);if(!$r||!is_dir($r)||!$base||!str_starts_with($r.DIRECTORY_SEPARATOR,$base.DIRECTORY_SEPARATOR))return self::err('plugin_not_found','Plugin directory not found.');return $r;}
 static function rel($p){$p=trim(str_replace('\\','/',wp_unslash((string)$p)),'/');if(!$p||str_contains($p,"\0")||preg_match('#(^|/)\.\.(/|$)#',$p))return self::err('invalid_path','Invalid relative path.');$e=strtolower(pathinfo($p,PATHINFO_EXTENSION));if(!in_array($e,self::$ext,true))return self::err('extension_not_allowed','File type not allowed.');return $p;}
 static function target($plugin,$path,$must=true){$r=self::root($plugin);if(is_wp_error($r))return$r;$rel=self::rel($path);if(is_wp_error($rel))return$rel;$f=$r.'/'.$rel;if($must){$real=realpath($f);if(!$real||!is_file($real)||is_link($real)||!str_starts_with($real,$r.DIRECTORY_SEPARATOR))return self::err('file_not_found','Plugin file not found.');$f=$real;}else{if(file_exists($f))return self::err('file_exists','Target already exists.');if(!is_dir(dirname($f))&&!wp_mkdir_p(dirname($f)))return self::err('mkdir_failed','Could not create target directory.');$pr=realpath(dirname($f));if(!$pr||!str_starts_with($pr.DIRECTORY_SEPARATOR,$r.DIRECTORY_SEPARATOR))return self::err('path_outside_plugin','Target path is outside plugin.');}return['root'=>$r,'rel'=>$rel,'full'=>$f];}
 static function valid($p,$c){if(strlen($c)>self::MAX)return self::err('file_too_large','File exceeds 2 MiB.');if('php'===strtolower(pathinfo($p,PATHINFO_EXTENSION))){try{token_get_all($c,TOKEN_PARSE);}catch(Throwable $e){return self::err('php_syntax_error',$e->getMessage());}}return true;}
 static function backup_file($r,$rel,$src){$u=wp_upload_dir();if(!empty($u['error']))return self::err('uploads_error',(string)$u['error']);$d=trailingslashit($u['basedir']).'farmneed-mcp-backups/plugins/'.basename($r).'/'.gmdate('Ymd-His').'-'.wp_generate_password(6,false,false).'/'.$rel;if(!wp_mkdir_p(dirname($d))||!copy($src,$d))return self::err('backup_failed','Could not create file backup.');return str_replace(trailingslashit(ABSPATH),'',$d);}
 static function write($f,$c){$t=tempnam(dirname($f),'.fn-');if(false===$t)return self::err('temp_failed','Could not create temporary file.');$n=file_put_contents($t,$c,LOCK_EX);if(false===$n||$n!==strlen($c)){@unlink($t);return self::err('write_failed','Could not write complete file.');}@chmod($t,file_exists($f)?(fileperms($f)&0777):0644);if(!@rename($t,$f)){@unlink($t);return self::err('rename_failed','Could not atomically replace file.');}clearstatcache(true,$f);return true;}
 static function list_files($i){$i=is_array($i)?$i:[];$r=self::root($i['plugin']??'');if(is_wp_error($r))return$r;$lim=max(1,min(2000,(int)($i['limit']??500)));$o=[];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($r,FilesystemIterator::SKIP_DOTS));foreach($it as$f){if(count($o)>=$lim)break;if($f->isLink()||!$f->isFile())continue;$rel=ltrim(str_replace('\\','/',substr($f->getPathname(),strlen($r))),'/');$e=strtolower(pathinfo($rel,PATHINFO_EXTENSION));$o[]=['path'=>$rel,'size'=>$f->getSize(),'sha256'=>hash_file('sha256',$f->getPathname()),'editable'=>in_array($e,self::$ext,true)&&$f->getSize()<=self::MAX];}return self::ok(['plugin'=>basename($r),'files'=>$o]);}
 static function read_file($i){$i=is_array($i)?$i:[];$f=self::target($i['plugin']??'',$i['path']??'',true);if(is_wp_error($f))return$f;$n=filesize($f['full']);if(false===$n||$n>self::MAX)return self::err('file_too_large','File exceeds 2 MiB.');$c=file_get_contents($f['full']);if(false===$c)return self::err('read_failed','Could not read file.');return self::ok(['plugin'=>basename($f['root']),'path'=>$f['rel'],'sha256'=>hash('sha256',$c),'content'=>$c]);}
 static function update_file($i){$i=is_array($i)?$i:[];$f=self::target($i['plugin']??'',$i['path']??'',true);if(is_wp_error($f))return$f;$cur=hash_file('sha256',$f['full']);$exp=strtolower((string)($i['expected_sha256']??''));if(!$exp||!hash_equals($cur,$exp))return self::err('conflict','File changed since read.',['current_sha256'=>$cur]);$c=(string)($i['content']??'');$v=self::valid($f['rel'],$c);if(is_wp_error($v))return$v;$b=self::backup_file($f['root'],$f['rel'],$f['full']);if(is_wp_error($b))return$b;$w=self::write($f['full'],$c);if(is_wp_error($w))return$w;return self::ok(['plugin'=>basename($f['root']),'path'=>$f['rel'],'sha256'=>hash('sha256',$c),'backup'=>$b]);}
 static function create_file($i){$i=is_array($i)?$i:[];$f=self::target($i['plugin']??'',$i['path']??'',false);if(is_wp_error($f))return$f;$c=(string)($i['content']??'');$v=self::valid($f['rel'],$c);if(is_wp_error($v))return$v;$w=self::write($f['full'],$c);if(is_wp_error($w))return$w;return self::ok(['plugin'=>basename($f['root']),'path'=>$f['rel'],'sha256'=>hash('sha256',$c)]);}
 static function backup_plugin($i){$i=is_array($i)?$i:[];$r=self::root($i['plugin']??'');if(is_wp_error($r))return$r;$u=wp_upload_dir();if(!empty($u['error']))return self::err('uploads_error',(string)$u['error']);$d=trailingslashit($u['basedir']).'farmneed-mcp-backups/plugins/'.basename($r).'/'.gmdate('Ymd-His').'-'.wp_generate_password(6,false,false).'/full';if(!wp_mkdir_p($d))return self::err('backup_failed','Could not create backup directory.');$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($r,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::SELF_FIRST);$n=0;$bytes=0;foreach($it as$f){if($f->isLink())continue;$rel=ltrim(str_replace('\\','/',substr($f->getPathname(),strlen($r))),'/');$to=$d.'/'.$rel;if($f->isDir()){wp_mkdir_p($to);continue;}$bytes+=$f->getSize();if($bytes>52428800)return self::err('backup_too_large','Plugin backup exceeds 50 MiB.');if(!wp_mkdir_p(dirname($to))||!copy($f->getPathname(),$to))return self::err('backup_failed','Could not copy all files.');$n++;}return self::ok(['plugin'=>basename($r),'files'=>$n,'bytes'=>$bytes,'backup'=>str_replace(trailingslashit(ABSPATH),'',$d)]);}
}
FN_MCP_Bootstrap::init();
